# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ewout's blog.
email: blog@ewoutvangossum.be
description: This is my personal blog. I write about programming stuff here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://denewout.github.io" # the base hostname & protocol for your site
comments: true
twitter_username: DenEwout
github_username:  DenEwout

# Build settings
markdown: kramdown
